version: 2.1
jobs:
  deploy-to-pages:
    docker:
      - image: cimg/node:lts

    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm package cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            sudo corepack enable
            corepack prepare pnpm@latest --activate
            pnpm config set store-dir .pnpm-store
      - run:
          name: Install dependencies
          command: pnpm install
      - run:
          name: Run the build step
          command: pnpm build
      - run:
          name: Deploy to cloudflare pages
          command: pnpx wrangler pages deploy dist --project-name=revised --commit-dirty=true
      - save_cache:
          name: Save pnpm package cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - .pnpm-store

  purge-cache:
    docker:
      - image: badouralix/curl-jq:latest
    steps:
      - run:
          name: Purge cloudflare cache
          command: |
            response=$(curl -s -X POST "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
              -H "X-Auth-Email: $CLOUDFLARE_EMAIL" \
              -H "X-Auth-Key: $CLOUDFLARE_API_KEY" \
              -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}')
            success=$(echo "$response" | jq -r '.success')
            if [[ "$success" == "false" ]]; then
              echo "Failed to purge the cache."
              echo ""
              echo $response | jq '.errors'
              exit 1
            else
              echo "Cache purged successfully."
              echo ""
              echo $response | jq '.result'
            fi

workflows:
  publish-to-pages-workflow:
    jobs:
      - deploy-to-pages
      - purge-cache:
          requires:
            - deploy-to-pages
